# Generated by Django 6.0.4 on 2026-05-07 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(help_text='Cédula o RUC', max_length=15, unique=True)),
                ('apellido', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.TextField()),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(default='', max_length=15)),
                ('estado_civil', models.CharField(choices=[('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('DIVORCIADO', 'Divorciado/a'), ('VIUDO', 'Viudo/a'), ('UNION_LIBRE', 'Unión Libre')], default='SOLTERO', max_length=20)),
                ('etnia', models.CharField(choices=[('MESTIZO', 'Mestizo/a'), ('INDIGENA', 'Indígena'), ('AFROECUATORIANO', 'Afroecuatoriano/a'), ('MONTUBIO', 'Montubio/a'), ('BLANCO', 'Blanco/a'), ('OTRO', 'Otro')], default='MESTIZO', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(help_text='Número de espacio (1,2,3...)', unique=True)),
                ('zona', models.CharField(choices=[('NORTE', 'Zona Norte'), ('SUR', 'Zona Sur'), ('ESTE', 'Zona Este'), ('OESTE', 'Zona Oeste'), ('CENTRO', 'Zona Centro'), ('VIP', 'Zona VIP')], default='NORTE', max_length=20)),
                ('tipo_espacio', models.CharField(choices=[('AUTO', 'Automóvil'), ('MOTO', 'Motocicleta'), ('CAMIONETA', 'Camioneta'), ('DISCAPACITADO', 'Persona con Discapacidad'), ('MUJER', 'Mujer Embarazada/Con Niños'), ('CARGA', 'Vehículo de Carga')], default='AUTO', max_length=20)),
                ('estado', models.CharField(choices=[('DISPONIBLE', '✅ Disponible'), ('OCUPADO', '🔴 Ocupado'), ('MANTENIMIENTO', '🔧 Mantenimiento'), ('RESERVADO', '📅 Reservado')], default='DISPONIBLE', max_length=20)),
                ('tarifa_hora', models.DecimalField(decimal_places=2, default=1.5, max_digits=6)),
                ('tarifa_hora_extra', models.DecimalField(decimal_places=2, default=2.0, max_digits=6)),
                ('piso', models.IntegerField(default=1, help_text='Número de piso')),
                ('sector', models.CharField(blank=True, help_text='Ej: Sector A, cerca del ascensor', max_length=50)),
                ('tiene_cargador_electrico', models.BooleanField(default=False)),
                ('tiene_seguridad', models.BooleanField(default=True)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Espacio',
                'verbose_name_plural': 'Espacios',
                'ordering': ['zona', 'piso', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(help_text='Ej: ABC-1234', max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.IntegerField(default=2020)),
                ('color', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('AUTO', 'Automóvil'), ('CAMIONETA', 'Camioneta'), ('MOTO', 'Motocicleta'), ('CAMION', 'Camión'), ('BUS', 'Bus'), ('FURGON', 'Furgoneta')], default='AUTO', max_length=20)),
                ('combustible', models.CharField(choices=[('GASOLINA', 'Gasolina Súper'), ('GASOLINA_ECO', 'Gasolina Eco'), ('DIESEL', 'Diésel'), ('ELECTRICO', 'Eléctrico'), ('HIBRIDO', 'Híbrido'), ('GAS', 'Gas Licuado')], default='GASOLINA', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='cobro.cliente')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cobro', models.CharField(blank=True, help_text='Número de ticket/factura', max_length=20, unique=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('horas_estacionado', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('minutos_estacionado', models.IntegerField(default=0)),
                ('valor_hora', models.DecimalField(decimal_places=2, default=1.5, max_digits=6)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, help_text='IVA 15% o 12% según tarifa', max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', '💵 Efectivo'), ('TARJETA_CREDITO', '💳 Tarjeta de Crédito'), ('TARJETA_DEBITO', '💳 Tarjeta de Débito'), ('TRANSFERENCIA', '🏦 Transferencia Bancaria'), ('YAPE', '📱 Yape'), ('PLIN', '📱 Plin'), ('TRANSACCION', '🔄 Transacción')], default='EFECTIVO', max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', '🟢 Activo (Vehículo estacionado)'), ('PAGADO', '✅ Pagado'), ('ANULADO', '❌ Anulado'), ('PENDIENTE', '⏳ Pendiente de pago')], default='ACTIVO', max_length=20)),
                ('tipo_tarifa', models.CharField(choices=[('HORA', 'Por Hora'), ('DIA', 'Por Día'), ('MES', 'Mensual'), ('SEMANA', 'Semanal')], default='HORA', max_length=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('factura_electronica', models.BooleanField(default=False)),
                ('factura_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que registró', max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('espacio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros', to='cobro.espacio')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='cobro.vehiculo')),
            ],
            options={
                'verbose_name': 'Cobro',
                'verbose_name_plural': 'Cobros',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
